name: Veracode container scanning

on: 
  push:
  workflow_dispatch:
    

jobs:

  container-scan:
      runs-on: ubuntu-latest
      name: container scan

      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: app:latest
      - name: docker ls
        run: |
          docker images 
        - name: checkout
          uses: actions/checkout@v2

        - name: container-scan action step
          id: container-scan
          uses: ./
          with:
            vid: ${{ secrets.VID }}
            vkey: ${{ secrets.VKEY }}
            command: "scan" 
            type: "directory"
            source: "./"
            format: "json"
            debug: 1
            fail_build: false
#